### ISSUE TITLE
【公式Web】メンバー紹介ページの写真を入れる

### ISSUE THREAD

**Issue by abarth500** [YokoyamaLab/YokoyamaLab-Official-Web#10]
Web掲載用の写真を撮ってメンバーページを更新する

- 写真のサイズは横400ピクセル/縦650ピクセル
- 画像はassets/img/profleに保存
    - https://github.com/YokoyamaLab/YokoyamaLab-Official-Web/tree/master/assets/img/profile
 
終わった人はこのスレッドの返信で連絡してください。

**Comment by abarth500** [comment]
テストテスト

**Comment by Kyabc** [comment]
更新済です (PR: https://github.com/YokoyamaLab/YokoyamaLab-Official-Web/pull/5, https://github.com/YokoyamaLab/YokoyamaLab-Official-Web/pull/9)

**Comment by Naoki-Kitamura** [comment]
あとで面倒なのでファイル名を英子文字で"名前-苗字"で統一してくださいね
